import SwiftUI

struct SplashView: View { @EnvironmentObject var state: AppState; @State private var show=false
    var body: some View { ZStack { HayTripTheme.navy.ignoresSafeArea(); VStack(spacing:14){ HayLogo(light:true).scaleEffect(show ? 1 : .88).opacity(show ? 1 : 0); Text("رحلتك تبدأ هنا").foregroundStyle(.white.opacity(.7)).font(.subheadline) }.task { withAnimation(.easeOut(duration: .8)){show=true}; try? await Task.sleep(for:.seconds(1.8)); state.go(.onboarding) } } }
}

struct OnboardingView: View { @EnvironmentObject var state: AppState; @State private var page=0
    let titles=["خطط لرحلتك بطريقتك","نساعدك تختار الأفضل","ونجهز لك الرحلة كاملة"]
    var body: some View { VStack(spacing:28){ Spacer(); ZStack{ Circle().fill(HayTripTheme.beige.opacity(.55)).frame(width:250,height:250); Image(systemName: page==0 ? "airplane" : page==1 ? "checkmark.seal" : "map").font(.system(size:64,weight:.light)).foregroundStyle(HayTripTheme.navy) }.animation(.easeInOut,value:page); Text(titles[page]).font(.system(size:30,weight:.bold)).multilineTextAlignment(.center).foregroundStyle(HayTripTheme.navy); Text("وكالة سفرك الذكية، بتجربة مصممة لك.").foregroundStyle(HayTripTheme.muted); Spacer(); HStack{ForEach(0..<3,id:\.self){i in Capsule().fill(i==page ? HayTripTheme.navy : HayTripTheme.beige).frame(width:i==page ? 24:7,height:7)}}; PrimaryButton(title:page<2 ? "التالي":"ابدأ رحلتك"){ if page<2 { withAnimation{page+=1} } else { state.go(.home) } }.padding(.horizontal,24).padding(.bottom,28) }.padding(.top,30).background(HayTripTheme.ivory.ignoresSafeArea()) }
}

struct HomeView: View { @EnvironmentObject var state: AppState; @State private var query=""
    var body: some View { ScrollView{ VStack(alignment:.leading,spacing:24){ HStack{HayLogo();Spacer();Image(systemName:"person.crop.circle").font(.title2)}; VStack(alignment:.leading,spacing:8){Text("إلى أين وجهتك القادمة؟").font(.system(size:32,weight:.bold));Text("احكِ لنا عن الرحلة، والباقي علينا.").foregroundStyle(HayTripTheme.muted)}; VStack(alignment:.leading,spacing:14){TextField("مثال: أبي رحلة لليابان 7 أيام بميزانية 7,000 ريال...",text:$query,axis:.vertical).lineLimit(4).padding(16).frame(minHeight:120,alignment:.top).background(.white).clipShape(RoundedRectangle(cornerRadius:20));PrimaryButton(title:"خطط رحلتي"){state.destination=query.isEmpty ? "طوكيو، اليابان":query;state.go(.request)}}; Text("اختر أسلوب الرحلة").font(.title3.bold()); ScrollView(.horizontal,showsIndicators:false){HStack{ForEach(["رحلة عائلية","شهر عسل","مغامرة","استرخاء","اقتصادية"],id:\.self){Text($0).padding(.horizontal,16).padding(.vertical,11).background(HayTripTheme.beige.opacity(.55)).clipShape(Capsule())}}} } }.padding(24).background(HayTripTheme.ivory.ignoresSafeArea()) }
}

struct TripRequestView: View { @EnvironmentObject var state: AppState
    var body: some View { ScrollView{VStack(alignment:.leading,spacing:20){Text("تفاصيل الرحلة").font(.system(size:30,weight:.bold));Text("خلنا نضبطها على ذوقك.").foregroundStyle(HayTripTheme.muted); LabeledContent("الوجهة"){TextField("طوكيو، اليابان",text:$state.destination).multilineTextAlignment(.trailing)}.padding().background(.white).clipShape(RoundedRectangle(cornerRadius:16));LabeledContent("التاريخ"){TextField("١ نوفمبر – ٧ نوفمبر",text:$state.dates).multilineTextAlignment(.trailing)}.padding().background(.white).clipShape(RoundedRectangle(cornerRadius:16));LabeledContent("الميزانية"){TextField("7000",text:$state.budget).keyboardType(.numberPad).multilineTextAlignment(.trailing)}.padding().background(.white).clipShape(RoundedRectangle(cornerRadius:16));LabeledContent("اهتماماتك"){TextField("تسوق، مطاعم، ثقافة...",text:$state.interests).multilineTextAlignment(.trailing)}.padding().background(.white).clipShape(RoundedRectangle(cornerRadius:16));PrimaryButton(title:"ابدأ التخطيط"){state.go(.processing)} }.padding(24)}.background(HayTripTheme.ivory.ignoresSafeArea()) }
}

struct ProcessingView: View { @EnvironmentObject var state: AppState; @State private var index=0; let steps=["نفهم طلبك","نبحث عن أفضل الخيارات","نقارن الرحلات والفنادق","نبني خطة رحلتك"]
    var body: some View { VStack(spacing:26){ZStack{Circle().stroke(HayTripTheme.beige,lineWidth:10).frame(width:92,height:92);Image(systemName:"airplane").font(.title).foregroundStyle(HayTripTheme.green)};Text(steps[index]).font(.title2.bold());ProgressView(value:Double(index),total:3).tint(HayTripTheme.green).frame(width:220)}.frame(maxWidth:.infinity,maxHeight:.infinity).background(HayTripTheme.ivory.ignoresSafeArea()).task{for i in 1..<steps.count{try? await Task.sleep(for:.seconds(0.9));withAnimation{index=i}};try? await Task.sleep(for:.seconds(0.7));state.go(.flights)} }
}

struct FlightResultsView: View { @EnvironmentObject var state: AppState
    var body: some View { VStack(alignment:.leading){Text("رحلات إلى طوكيو").font(.largeTitle.bold()).padding(.horizontal,24);Text("اختر رحلتين للمقارنة").foregroundStyle(HayTripTheme.muted).padding(.horizontal,24);ScrollView{VStack(spacing:14){ForEach(MockData.flights){f in FlightCard(flight:f,selected:state.compareFlightIDs.contains(f.id)){if state.compareFlightIDs.contains(f.id){state.compareFlightIDs.remove(f.id)}else if state.compareFlightIDs.count<2{state.compareFlightIDs.insert(f.id)}}}}.padding(24)};PrimaryButton(title:"قارن الخيارات (\(state.compareFlightIDs.count))",disabled:state.compareFlightIDs.count != 2){state.go(.flightCompare)}.padding(24)}.background(HayTripTheme.ivory.ignoresSafeArea()) }
}

struct FlightCard: View { let flight:Flight; let selected:Bool; let action:()->Void
    var body: some View {Button(action:action){VStack(alignment:.leading,spacing:14){HStack{Text(flight.airline).font(.headline);Spacer();Text("\(flight.price) ر.س").font(.title3.bold())};HStack{VStack(alignment:.leading){Text(flight.departure);Text(flight.from).font(.caption).foregroundStyle(HayTripTheme.muted)};Spacer();VStack{Text(flight.duration).font(.caption);Rectangle().fill(HayTripTheme.beige).frame(height:2).frame(width:65);Text(flight.stops).font(.caption).foregroundStyle(HayTripTheme.muted)};Spacer();VStack(alignment:.trailing){Text(flight.arrival);Text(flight.to).font(.caption).foregroundStyle(HayTripTheme.muted)}};if let reason=flight.reason{Text(reason).font(.caption).foregroundStyle(HayTripTheme.green)};HStack{Text(flight.baggage).font(.caption);Spacer();Image(systemName:selected ? "checkmark.circle.fill":"circle").foregroundStyle(selected ? HayTripTheme.green:HayTripTheme.muted)}}.foregroundStyle(HayTripTheme.ink).hayCard()}.buttonStyle(.plain)}
}

struct FlightComparisonView: View { @EnvironmentObject var state:AppState; var flights:[Flight]{MockData.flights.filter{state.compareFlightIDs.contains($0.id)}}
    var body: some View {ScrollView{VStack(alignment:.leading,spacing:18){Text("قارن واختار").font(.largeTitle.bold());ForEach(flights){f in VStack(alignment:.leading,spacing:12){Text(f.airline).font(.headline);HStack{Stat(title:"السعر",value:"\(f.price) ر.س");Stat(title:"المدة",value:f.duration);Stat(title:"التوقف",value:f.stops)};Text(f.reason ?? "خيار جيد إذا كان السعر أولوية.").font(.subheadline).foregroundStyle(HayTripTheme.muted);PrimaryButton(title:"اختيار الرحلة"){state.selectedFlightID=f.id;state.go(.hotels)}}.hayCard()};Text("مساعدة HayTrip").font(.title2.bold());Text("الأرخص ليس بالضرورة الأفضل. نرجح الخيار الذي يحقق أفضل توازن بين السعر والوقت والراحة.").foregroundStyle(HayTripTheme.green).hayCard()}.padding(24)}.background(HayTripTheme.ivory.ignoresSafeArea())}
}

struct HotelResultsView: View { @EnvironmentObject var state:AppState
    var body: some View {VStack(alignment:.leading){Text("فنادق مقترحة").font(.largeTitle.bold()).padding(.horizontal,24);Text("اختر فندقين للمقارنة").foregroundStyle(HayTripTheme.muted).padding(.horizontal,24);ScrollView{VStack(spacing:14){ForEach(MockData.hotels){h in HotelCard(hotel:h,selected:state.compareHotelIDs.contains(h.id)){if state.compareHotelIDs.contains(h.id){state.compareHotelIDs.remove(h.id)}else if state.compareHotelIDs.count<2{state.compareHotelIDs.insert(h.id)}}}}.padding(24)};PrimaryButton(title:"قارن الخيارات (\(state.compareHotelIDs.count))",disabled:state.compareHotelIDs.count != 2){state.go(.hotelCompare)}.padding(24)}.background(HayTripTheme.ivory.ignoresSafeArea())}
}

struct HotelCard:View{let hotel:Hotel;let selected:Bool;let action:()->Void;var body:some View{Button(action:action){VStack(alignment:.leading,spacing:12){RoundedRectangle(cornerRadius:16).fill(HayTripTheme.beige).frame(height:130).overlay(Image(systemName:"building.2").font(.largeTitle).foregroundStyle(HayTripTheme.navy));HStack{Text(hotel.name).font(.headline);Spacer();Label(String(format:"%.1f",hotel.rating),systemImage:"star.fill").foregroundStyle(HayTripTheme.green)};Text(hotel.location).foregroundStyle(HayTripTheme.muted);HStack{Text("\(hotel.totalPrice) ر.س").font(.title3.bold());Text("لـ \(hotel.nights) ليالي").font(.caption).foregroundStyle(HayTripTheme.muted);Spacer();Image(systemName:selected ? "checkmark.circle.fill":"circle").foregroundStyle(selected ? HayTripTheme.green:HayTripTheme.muted)};if let reason=hotel.reason{Text(reason).font(.caption).foregroundStyle(HayTripTheme.green)}}.foregroundStyle(HayTripTheme.ink).hayCard()}.buttonStyle(.plain)} }

struct HotelComparisonView:View{@EnvironmentObject var state:AppState;var hotels:[Hotel]{MockData.hotels.filter{state.compareHotelIDs.contains($0.id)}};var body:some View{ScrollView{VStack(alignment:.leading,spacing:18){Text("قارن واختار").font(.largeTitle.bold());ForEach(hotels){h in VStack(alignment:.leading,spacing:12){Text(h.name).font(.headline);HStack{Stat(title:"السعر",value:"\(h.totalPrice) ر.س");Stat(title:"التقييم",value:"\(h.rating)");Stat(title:"المسافة",value:h.distance)};Text("\(h.room) • \(h.cancellation)").font(.subheadline).foregroundStyle(HayTripTheme.muted);Text(h.reason ?? "خيار مناسب لمن يفضل خفض التكلفة.").foregroundStyle(HayTripTheme.green);PrimaryButton(title:"اختيار الفندق"){state.selectedHotelID=h.id;state.go(.building)}}.hayCard()}}.padding(24)}.background(HayTripTheme.ivory.ignoresSafeArea())}}

struct Stat:View{let title:String;let value:String;var body:some View{VStack(alignment:.leading,spacing:4){Text(title).font(.caption).foregroundStyle(HayTripTheme.muted);Text(value).font(.subheadline.bold())}.frame(maxWidth:.infinity,alignment:.leading)}}

struct TripBuildingView:View{@EnvironmentObject var state:AppState;var body:some View{VStack(spacing:24){Image(systemName:"map").font(.system(size:56,weight:.light)).foregroundStyle(HayTripTheme.green);Text("نجهز لك خطة رحلتك").font(.title.bold());Text("نرتب الأيام حول رحلتك وفندقك واختياراتك.").foregroundStyle(HayTripTheme.muted);ProgressView()}.frame(maxWidth:.infinity,maxHeight:.infinity).background(HayTripTheme.ivory.ignoresSafeArea()).task{try? await Task.sleep(for:.seconds(1.6));state.go(.itinerary)}}}

struct ItineraryView:View{@EnvironmentObject var state:AppState
    var days:[Day]{let arrival=state.selectedFlight?.arrival ?? "16:50";let hotel=state.selectedHotel?.name ?? "الفندق";return(1...7).map{n in Day(id:"d\(n)",number:n,title:n==1 ? "الوصول والاستقرار":"استكشاف الوجهة",items:n==1 ? [AgendaItem(id:"a\(n)1",time:arrival,title:"الوصول إلى طوكيو",detail:"عبر \(state.selectedFlight?.airline ?? "رحلتك")"),AgendaItem(id:"a\(n)2",time:"18:30",title:"تسجيل الدخول",detail:hotel),AgendaItem(id:"a\(n)3",time:"20:30",title:"عشاء قريب",detail:"اختيار HayTrip")] : [AgendaItem(id:"a\(n)1",time:"09:00",title:"الإفطار",detail:hotel),AgendaItem(id:"a\(n)2",time:"11:00",title:"جولة اليوم",detail:"تجربة محلية مختارة حسب اهتماماتك"),AgendaItem(id:"a\(n)3",time:"19:30",title:"عشاء",detail:"مطعم مقترح قريب") ]}}
    var shareText:String{"رحلتي مع HayTrip\n\(state.destination)\n\(state.totalCost) ر.س"}
    var body:some View{ScrollView{VStack(alignment:.leading,spacing:20){HayLogo();Text("خطة رحلتك").font(.system(size:34,weight:.bold));Text("\(state.destination) • \(state.travelers)").foregroundStyle(HayTripTheme.muted);VStack(alignment:.leading,spacing:10){HStack{Text("الإجمالي");Spacer();Text("\(state.totalCost) ر.س").font(.title2.bold())};HStack{Text(state.balance >= 0 ? "المتبقي":"التجاوز");Spacer();Text("\(abs(state.balance)) ر.س").foregroundStyle(state.balance >= 0 ? HayTripTheme.green:.red).bold()}}.hayCard();ForEach(days){day in VStack(alignment:.leading,spacing:14){Text("اليوم \(day.number) • \(day.title)").font(.title3.bold());ForEach(day.items){item in HStack(alignment:.top,spacing:14){Text(item.time).font(.caption.bold()).frame(width:48,alignment:.leading);VStack(alignment:.leading,spacing:4){Text(item.title).font(.headline);Text(item.detail).font(.caption).foregroundStyle(HayTripTheme.muted)}}}.padding(.top,4)}.hayCard()};ShareLink(item:shareText){Text("مشاركة الخطة").font(.headline).foregroundStyle(.white).frame(maxWidth:.infinity).padding().background(HayTripTheme.green).clipShape(RoundedRectangle(cornerRadius:16))}.padding(.vertical,8)}.padding(24)}.background(HayTripTheme.ivory.ignoresSafeArea())}
}